# Generated by Django 5.0.6 on 2024-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_comment_created_date_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=0.0004943153732081067, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
