# Generated by Django 5.0.6 on 2024-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0006_product_categoryy_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryy',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
